name: Terraform Deploy

on:
  push:
    branches:
      - main
      - test
      - uat
      - prod

jobs:
  deploy_dev:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: |
        pwd
        cd terraform/environments/dev
        pwd
        terraform init \
          -input=false

    - name: Terraform Validate
      run: |
        pwd
        cd terraform/environments/dev 
        terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan terraform/environments/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

  deploy_test:
    name: Deploy to Test
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init infra/environments/test

    - name: Terraform Validate
      run: terraform validate infra/environments/test

    - name: Terraform Plan
      run: terraform plan -out=tfplan infra/environments/test

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

  deploy_uat:
    name: Deploy to UAT
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init infra/environments/uat

    - name: Terraform Validate
      run: terraform validate infra/environments/uat

    - name: Terraform Plan
      run: terraform plan -out=tfplan infra/environments/uat

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

  deploy_prod:
    name: Deploy to Prod
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init infra/environments/prod

    - name: Terraform Validate
      run: terraform validate infra/environments/prod

    - name: Terraform Plan
      run: terraform plan -out=tfplan infra/environments/prod

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
